MiPrimeraAplicacionMVCConCapas/Controllers/CamaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capa_Negocio;
using Capa_Entidad;
namespace MiPrimeraAplicacionMVCConCapas.Controllers
{
    public class CamaController : Controller
    {
        // GET: Cama
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult listarCama() 
        {
            CamaBL oCamaBL = new CamaBL();
            return Json( oCamaBL.listarCama(),JsonRequestBehavior.AllowGet);
        
        }

        public JsonResult FiltrarCama(string nombre)
        {
            CamaBL oCamaBL = new CamaBL();
            return Json(oCamaBL.FiltrarCama(nombre), JsonRequestBehavior.AllowGet);

        }
    }
}

MiPrimeraAplicacionMVCConCapas/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capa_Negocio;
using Capa_Entidad;

namespace MiPrimeraAplicacionMVCConCapas.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult listarMarca() 
        {
            MarcaBL marcaBL = new MarcaBL();
            return Json(marcaBL.listarMarca2(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult FiltrarMarca(string nombre)
        {
            MarcaBL marcaBL = new MarcaBL();
            return Json(marcaBL.filtrarMarca(nombre), JsonRequestBehavior.AllowGet);
        }


        public JsonResult recuperarMarca(int id)
        {
            MarcaBL marcaBL = new MarcaBL();
            return Json(marcaBL.recuperarMarca(id), JsonRequestBehavior.AllowGet);
        }

        public int eliminarMarca(int iidMarca) 
        {
            MarcaBL marcaBL = new MarcaBL();
            return marcaBL.eliminarMarca(iidMarca);
        }

        public int guardarMarca(MarcaCLS oMarcaCLS) 
        {
            MarcaBL marcaBL = new MarcaBL();
            return marcaBL.guardarMarca(oMarcaCLS);
        }

    }
}

MiPrimeraAplicacionMVCConCapas/Controllers/ProductoController.cs
using Capa_Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiPrimeraAplicacionMVCConCapas.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult lista()
        {
            ProductoBL obj = new ProductoBL();
            return Json(obj.listarProducto(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult filtrarProductoPorNombre(string nombreProducto)
        {
            ProductoBL obj = new ProductoBL();
            return Json(obj.filtrarProductos(nombreProducto), JsonRequestBehavior.AllowGet);
        }

    }
}

MiPrimeraAplicacionMVCConCapas/Controllers/TipoHabitacionController.cs
using Capa_Entidad;
using Capa_Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiPrimeraAplicacionMVCConCapas.Controllers
{
    public class TipoHabitacionController : Controller
    {
        // GET: TipoHabitacion
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Inicio()
        {
            return View();
        }

        public ActionResult VistaPruebaInicio()
        {
            return View();
        }

        public string cadena()
        {
            return "123";
        }

        public int numero()
        {
            return 5;
        }

        //public List<TipoHabitacionCLS> lista()
        //{
        //    TipoHabitacionBL obj = new TipoHabitacionBL();
        //    return obj.listarTipoHabitacion();
        //}
        // [{"id":1,"nombre":"Simple","descripcion":"Solo para uno"},{"id":2,"nombre":"Doble","descripcion":"Hecho para casados"}]
        public JsonResult lista()
        {
            TipoHabitacionBL obj = new TipoHabitacionBL();
            return Json(obj.listarTipoHabitacion(),JsonRequestBehavior.AllowGet);
        }

        public JsonResult filtrarTipoHabitacionPorNombre(string nombreHabitacion)
        {
            TipoHabitacionBL obj = new TipoHabitacionBL();
            return Json(obj.FiltrarTipoHabitacion(nombreHabitacion), JsonRequestBehavior.AllowGet);
        }

        public int guardarDatos(TipoHabitacionCLS oTipoHabitacionCLS) 
        {
            TipoHabitacionBL obj = new TipoHabitacionBL();
            return obj.guardarTipoHabitacion(oTipoHabitacionCLS);

        }

        public JsonResult recuperarTipoHabitacion(int id) 
        {
            TipoHabitacionBL obj = new TipoHabitacionBL();
            return Json(obj.recuperarTipoHabitacion(id), JsonRequestBehavior.AllowGet);
        }

        public int EliminarTipoHabitacion(int id) 
        {
            TipoHabitacionBL obj = new TipoHabitacionBL();
            return obj.EliminarTipoHabitacion(id);
        }



    }
}

MiPrimeraAplicacionMVCConCapas/Views/Cama/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Listado Cama</h2>

<div id="divTabla">

</div>

<script src="~/Scripts/generic.js"></script>
<script src="~/Scripts/cama.js"></script>

MiPrimeraAplicacionMVCConCapas/Views/Marca/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Listado Marca</h2>

@*<div class="input-group mb-3">
    <input type="text" class="form-control"
           id="txtNombreMarca"
           onkeyup="Buscar()"
           placeholder="ingrese el nombre de la marca" />


</div>*@


<div id="divTabla">

</div>

<script src="~/Scripts/generic.js"></script>
<script src="~/Scripts/Marca.js"></script>

MiPrimeraAplicacionMVCConCapas/Views/Producto/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Lista Productos</h2>

<div class="input-group mb-3">
    <input type="text" class="form-control"
           id="txtNombreProducto"
           onkeyup="Buscar()"
           placeholder="ingrese el nombre del producto" />

 
</div>


<div id="divTabla">

</div>


<script src="~/Scripts/generic.js"></script>
<script src="~/Scripts/producto.js"></script>

MiPrimeraAplicacionMVCConCapas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>

   
    <div class="nav-side-menu">
        <div class="tasi">
            <div class="brand">@*<img src="//tecrubeliyim.com/wp-content/uploads/logoS.png" width="150">*@<!-- /Web-Doktoru --></div>
            <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

            <div class="menu-list">

                <ul id="menu-content" class="menu-content collapse out">
                    <li>
                        @Html.ActionLink("Tipo Habitacion", "Index", "TipoHabitacion",
                       new { area = "" }, new { @class = "nav-link js-scroll-trigger" })

                    </li>


                    <li>
                        @Html.ActionLink("Cama", "Index", "Cama",
                       new { area = "" }, new { @class = "nav-link js-scroll-trigger" })

                    </li>

                    <li>
                        @Html.ActionLink("Marca", "Index", "Marca",
                       new { area = "" }, new { @class = "nav-link js-scroll-trigger" })

                    </li>
                    <li>
                        @Html.ActionLink("Producto", "Index", "Producto",
                         new { area = "" }, new { @class = "nav-link js-scroll-trigger" })
                    </li>
                    <li>
                        <a href="#digerleri">
                            Devam edin...
                        </a>
                    </li>
                    <!--li data-toggle="collapse" data-target="#new" class="collapsed">
              <a href="#"><i class="fa fa-car fa-lg"></i> New <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="new">
              <li>New New 1</li>
              <li>New New 2</li>
              <li>New New 3</li>
            </ul-->
                </ul>
            </div>
        </div>
    </div></div>
    <div  style="margin-left:230px"  >
        @RenderBody()
    </div>
  
    <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />

    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MiPrimeraAplicacionMVCConCapas/Views/TipoHabitacion/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Tipo Habitacion</h2>

<fieldset class="container mb-4">
    <legend> Datos de tipo Habitacion </legend>

    <form id="frmTipoHabitacion" method="post">

        <div class="row">
            <div class="mb-3 col-md-6" >
                <label>Id tipo Habitacion</label>
                <input type="text" class="form-control"
                       name="id" value="0" readonly />

            </div>

            <div class="mb-3 col-md-6">
                <label>Nombre tipo habitacion</label>
                <input type="text" class="form-control"
                       name="nombre" />

            </div>
        </div>

        <div class="row">

            <div class="mb-3 col-md-12">
                <label>Descripcion tipo habitacion</label>
                <input type="text" class="form-control"
                       name="descripcion" />

            </div>

        </div>
       



    </form>

        <button class="btn btn-primary" onclick="GuardarDatos()">Aceptar</button>
        <button class="btn btn-danger" onclick="Limpiar()">Limpiar</button>
   

</fieldset>

<div class="mb-3">
    <input type="text" class="form-control" 
          id="txtNombreTipoHabitacion"
           placeholder="ingrese el nombre tipo habitacion" />

    <button class="btn btn-primary"
            onclick="Buscar()"
            type="button" id="btnNombreTipoHabitacion">Buscar
    </button>
</div>


<div id="divTabla" >

</div>

<script src="~/Scripts/sweetalert.js"></script>
<script src="~/Scripts/generic.js"></script>
<script src="~/Scripts/tipohabitacion.js"></script>

MiPrimeraAplicacionMVCConCapas/Views/TipoHabitacion/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
}

<h2>Vista Inicio</h2>

MiPrimeraAplicacionMVCConCapas/Views/TipoHabitacion/VistaPruebaInicio.cshtml
@{
    ViewBag.Title = "VistaPruebaInicio";
}

<h2>VistaPruebaInicio</h2>